-- GENERATED BY DatabaseCreator.cs
-- Copyright: Josh Comley, 2013
-- 04/09/2016 22:14:30
-- Also used in 'Start new project.linq'

USE [master]

-- Create data database
IF db_id('BugExample.App.Data') IS NOT NULL
BEGIN
	ALTER DATABASE [BugExample.App.Data] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE [BugExample.App.Data]
END

-- Create standard login
DECLARE @spidstr varchar(8000)
IF EXISTS 
    (SELECT name  
     FROM master.sys.server_principals
     WHERE name = 'hyperpragiaLogin')
BEGIN
	SET @spidstr = NULL
	SELECT @spidstr=coalesce(@spidstr,'' )+'kill '+convert(varchar, session_id)+ '; '
	FROM sys.dm_exec_sessions WHERE login_name = 'hyperpragiaLogin'
	IF LEN(@spidstr) > 0
	BEGIN
		EXEC(@spidstr)
	END

	ALTER LOGIN [hyperpragiaLogin] DISABLE;
	DROP LOGIN [hyperpragiaLogin]
END

-- Create migrations login
IF EXISTS 
    (SELECT name  
     FROM master.sys.server_principals
     WHERE name = 'repulsingLogin')
BEGIN
	SET @spidstr = NULL
	SELECT @spidstr=coalesce(@spidstr,'' )+'kill '+convert(varchar, session_id)+ '; '
	FROM sys.dm_exec_sessions WHERE login_name = 'repulsingLogin'

	IF LEN(@spidstr) > 0
	BEGIN
		EXEC(@spidstr)
	END

	DROP LOGIN [repulsingLogin]
END
